---
# task install

- name: disable selinux
  selinux:
    state: disabled

- name: install dependencies
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - docker
    - epel-release
    - git

- name: install python-docker-py
  yum:
    name: python-docker-py
    state: present
  when: "ansible_version.full < '2.6.0'"

- name: install pip
  yum:
    name: python-pip
    state: present
  when: "ansible_version.full >= '2.6.0'"

- name: pip uninstall docker-py
  pip:
    name: docker-py
    state: absent
  when: "ansible_version.full >= '2.6.0'"

- name: pip install docker-compose
  pip:
    name: docker-compose
  when: "ansible_version.full >= '2.6.0'"

- name: configure docker service
  service:
    name: docker
    enabled: yes
    state: started

- name: clone eyesofindicator git project
  git:
    repo: "{{ eoi_repo }}"
    dest: "{{ eoi_repo_dir }}"
    version: "{{ eoi_version }}"
    update: "{{ eoi_keep_updated }}"
    force: yes
    accept_hostkey: yes

- name: build docker image
  docker_image:
    path: "{{ eoi_repo_dir }}"
    name: "{{ eoi_image }}"
    tag: "{{ eoi_version }}"

- name: create required directories
  file:
    path: "{{ item }}"
    mode: 0755
    state: directory
    owner: root
    group: root
  with_items:
    - "{{ eoi_install_dir }}"
    - "{{ eoi_install_dir }}/{{ eoi_container }}"
    - "{{ eoi_install_dir }}/{{ eoi_container }}/assets"
    - "{{ eoi_install_dir }}/{{ eoi_container }}/dashboards"
    - "{{ eoi_install_dir }}/{{ eoi_container }}/config"
    - "{{ eoi_install_dir }}/{{ eoi_container }}/jobs"
    - "{{ eoi_install_dir }}/{{ eoi_container }}/lib-eoi"
    - "{{ eoi_install_dir }}/{{ eoi_container }}/widgets"
    - "{{ eoi_install_dir }}/{{ eoi_container }}/public"

- name: copy default files
  copy:
    src: "{{ role_path }}/files/defaults/"
    dest: "{{ eoi_install_dir }}/{{ eoi_container }}/"

- name: run docker container
  docker_container:
    name: "{{ eoi_container }}"
    image: "{{ eoi_image }}:{{ eoi_version }}"
    state: started
    restart_policy: always
    ports:
    - "{{ eoi_port }}:3030"
    env:
      APKS: "{{ eoi_apks }}"
      GEMS: "{{ eoi_gems }}"
      WIDGETS: "{{ eoi_widgets }}"
    volumes:
      - "{{ eoi_install_dir }}/{{ eoi_container }}/assets:/assets"
      - "{{ eoi_install_dir }}/{{ eoi_container }}/dashboards:/dashboards"
      - "{{ eoi_install_dir }}/{{ eoi_container }}/config:/config"
      - "{{ eoi_install_dir }}/{{ eoi_container }}/jobs:/jobs"
      - "{{ eoi_install_dir }}/{{ eoi_container }}/lib-eoi:/lib-eoi"
      - "{{ eoi_install_dir }}/{{ eoi_container }}/widgets:/widgets"
      - "{{ eoi_install_dir }}/{{ eoi_container }}/public:/public"
